modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="mobs_brawl"
version="1.0.0"
displayName="mobs_brawl"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="bleuf, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mobs_brawl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



